/*
 * Seq_Interface.c
 *
 * Created: 3/23/2022 3:29:46 PM
 *  Author: g_h_a
 */ 
#include "Seg_Private.h"

void SEVENSEG_Initialize(void){
DIO_SetPinDirection(SEVENSEG_DATA_PRT,SEVENSEG_DATA_A,SEVENSEG_OUTPUT);
DIO_SetPinDirection(SEVENSEG_DATA_PRT,SEVENSEG_DATA_B,SEVENSEG_OUTPUT);
DIO_SetPinDirection(SEVENSEG_DATA_PRT,SEVENSEG_DATA_C,SEVENSEG_OUTPUT);
DIO_SetPinDirection(SEVENSEG_DATA_PRT,SEVENSEG_DATA_D,SEVENSEG_OUTPUT);

DIO_SetPinDirection(SEVENSEG_CTRL_PRT,SEVENSEG_CTRL_EN1,SEVENSEG_OUTPUT);
DIO_SetPinDirection(SEVENSEG_CTRL_PRT,SEVENSEG_CTRL_EN2,SEVENSEG_OUTPUT);
DIO_SetPinDirection(SEVENSEG_CTRL_PRT,SEVENSEG_CTRL_DOT,SEVENSEG_OUTPUT);
}

void SEVENSEG_OFF(void){
	DIO_SetPinDirection(SEVENSEG_DATA_PRT,SEVENSEG_DATA_A,SEVENSEG_INPUT);
	DIO_SetPinDirection(SEVENSEG_DATA_PRT,SEVENSEG_DATA_B,SEVENSEG_INPUT);
	DIO_SetPinDirection(SEVENSEG_DATA_PRT,SEVENSEG_DATA_C,SEVENSEG_INPUT);
	DIO_SetPinDirection(SEVENSEG_DATA_PRT,SEVENSEG_DATA_D,SEVENSEG_INPUT);

	DIO_SetPinDirection(SEVENSEG_CTRL_PRT,SEVENSEG_CTRL_EN1,SEVENSEG_INPUT);
	DIO_SetPinDirection(SEVENSEG_CTRL_PRT,SEVENSEG_CTRL_EN2,SEVENSEG_INPUT);
	DIO_SetPinDirection(SEVENSEG_CTRL_PRT,SEVENSEG_CTRL_DOT,SEVENSEG_INPUT);
}              
void SEVENSEG_Enable1(void){
	DIO_SetPinValue(SEVENSEG_CTRL_PRT,SEVENSEG_CTRL_EN1,SEVENSEG_HIGH);
}
void SEVENSEG_Disable1(void){
	DIO_SetPinValue(SEVENSEG_CTRL_PRT,SEVENSEG_CTRL_EN1,SEVENSEG_LOW);
}

void SEVENSEG_Enable2(void){
	DIO_SetPinValue(SEVENSEG_CTRL_PRT,SEVENSEG_CTRL_EN2,SEVENSEG_HIGH);
}
void SEVENSEG_Disable2(void){
	DIO_SetPinValue(SEVENSEG_CTRL_PRT,SEVENSEG_CTRL_EN2,SEVENSEG_LOW);
}

void SEVENSEG_DOT_Enable(void){
	DIO_SetPinValue(SEVENSEG_CTRL_PRT,SEVENSEG_CTRL_DOT,SEVENSEG_HIGH);
}
void SEVENSEG_DOT_Disable(void){
	DIO_SetPinValue(SEVENSEG_CTRL_PRT,SEVENSEG_CTRL_DOT,SEVENSEG_LOW);
}

void SEVENSEG_Display(uint8_t number){
	uint8_t num1 = number%10;
	uint8_t num2 = number/10;
	SEVENSEG= (num1 << 4);
	SEVENSEG_Enable1();
	SEVENSEG_Disable2();
	_delay_ms(1);
	SEVENSEG= (num2 << 4);
	SEVENSEG_Disable1();
	SEVENSEG_Enable2();
	_delay_ms(1);
}